# Generated by Django 5.2.5 on 2026-03-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_userpreference_id_orderproposal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproposal",
            name="description",
        ),
    ]
