# Generated by Django 5.2.5 on 2026-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_orderproposal_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproposal",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderproposal",
            name="sender_role",
            field=models.CharField(
                choices=[("customer", "Customer"), ("provider", "Provider")],
                default="customer",
                max_length=10,
            ),
        ),
    ]
