# Generated by Django 5.2.5 on 2026-03-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_orderproposal_message_orderproposal_sender_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproposal",
            name="message",
        ),
    ]
